//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyProduct("Sample.Messages")]
[assembly: System.Reflection.AssemblyTitle("Sample.Messages")]
[assembly: System.Reflection.AssemblyCompany("CRAFT")]
[assembly: System.Reflection.AssemblyCopyright("© CRAFT 2017")]
[assembly: System.Reflection.AssemblyVersion("1.4.5.0")]
[assembly: System.Reflection.AssemblyFileVersion("1.4.5.0")]
[assembly: System.Reflection.AssemblyInformationalVersion("1.4.5.0")]


